### ISSUE TITLE
Error message with "recognize" function

### ISSUE THREAD

**Issue by anaverahrami** [shyamblast/Koogu#3]
I'm running into an issue with the "recognize" function in a block of code related to model evaluation and can't seem to figure out how to get past this. I've triple-checked that there are no typos in the code and have tried clearing and rerunning the code a few times now but can't get past the error. I have also tried entering lower batch sizes and this isn't doing the trick either. A screenshot of the error message is below. Thanks so much for any help you may be able to provide with this!
![Screenshot 2023-04-11 at 2 56 58 PM](https://user-images.githubusercontent.com/129873027/231823158-22cb0e6d-d886-45fb-8f7c-850685cc0f5d.png)

**Comment by shyamblast** [comment]
It's hard to pinpoint where the issue is just by looking at this screenshot. It very likely pertains to how Colab is being used, and less likely that it is an issue in Koogu. The error message points that there is a threading issue (which is usually at the system level). The issue could lie in whether or not you had mounted the "My Drive" properly, maybe one of the audio files has an issue (it may have had an issue when copying over from your local computer), maybe there isn't enough space left on your "My Drive" to write out the results, or maybe the resource that Google allocated for you to run the notebook had an issue (or you have used up your 'free' allocation time for the day).

Can you try restarting the notebook instance, run the earlier cells which mount the drive and assigns variables, and then then re run this cell?

If that still fails, try pointing `test_audio_root` to a single audio file (instead of pointing it to a directory) and try the above steps again. That might help us get closer to the source of the problem.

**Comment by anaverahrami** [comment]
Hey Shyam,

Thanks so much for this helpful feedback. I cleared up some of my google drive space and gave running everything another go but got the same error. Then I tried pointing test_audio_root to a single file as you suggested and the cell with the "recognize" function is now producing this error:

ERROR:koogu.utils:Processing /content/drive/My Drive/Koogu_GunshotClassifier/test_audio/MDF_0.5km_nn104_34dB_20211027_080001.wav generated an exception: BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')
No files processed

I just double-checked the sound file and it's playing the sound alright, so don't think it's been corrupted or anything. Any thoughts on what I might try next?

Thanks so much!
Ana

p.s. hope you're well :)

**Comment by shyamblast** [comment]
Thanks for giving access to your Colab notebook & data. It helped me narrow down the issue.
It turns out that your audio files are about 1.3 GB each. That's huge, especially when Koogu attempts to load the entire file into memory, apply any pre-processing operations, and convert to spectrogram chunks; all in the available RAM. Below is a screenshot of the RAM usage on Colab. The "exception" reported is because doing all of the aforemeitioned operations requires a lot more RAM than what free Colab offers.
![image](https://user-images.githubusercontent.com/44062292/233842088-a26e5c5c-d52e-47dd-96be-d018cf0aefac.png)

A quick and easy solution is to break up your audio files before running `recognize()`.
A bit more involved alternative would be to handle audio-processing yourself (could include using internal components from the `Data` module) and then use `koogu.inference.analyze_clips()` to bring about recognition.

**Comment by anaverahrami** [comment]
Got it, thanks for troubleshooting this! I will try breaking up the audio files before running the code and hopefully that will help!
