### ISSUE TITLE
Issue with data preprocessing

### ISSUE THREAD

**Issue by crondeaustj** [shyamblast/Koogu#6]
Hello,
I am using Koogu to make a model to recognize 3-second clips that I have put in directories which correspond to my labels. I am running into an issue when creating `clip_counts` from `preprocess.from_top_level_dirs()` with the following code:
```
clip_counts = preprocess.from_top_level_dirs(
    data_settings['audio_settings'], 
    class_dirs, audio_root, 
    output_root=prepared_audio_dir
)
```
It outputs counts that are incorrect. For example, in my `audio_root` directory "A", I have 1100 files, and also 1100 corresponding prepared files in the `prepared` directory, but the `clip_counts` shows a count of 1700 files for this directory. Because of that, I am unable to move forward with the code and keep getting errors when trying to implementing the feeder. 

I have noticed that clips from one of my two sources for data seem to be counted twice. For example, in the directory for class "A" in the example above, I have 500 files from my first source and 600 files from my second source (500 + (2*600) = 1700), and this phenomenon seems to be consistent over my data. All files are exactly 3-second long WAV clips, but the first source has a 44.1kHz sampling rate and the second source (the one that seems to be counted twice) has a 22.05kHz sampling rate. 

Here are my `data_settings`, in case it can help find the problem:
```
data_settings = {
    # Settings for handling raw audio
    'audio_settings': {
        'clip_length': 3.0,
        'clip_advance': 3.0,
        'desired_fs': 48000
    },

    # Settings for converting audio to a time-frequency (tf) representation
    'spec_settings': {
        'win_len': 0.512,
        'win_overlap_prc': 0.5,
        'bandwidth_clip': [3000, 10000]
    }
}
```

What do you think can be the source of the issue, and how can I fix it?

**Comment by shyamblast** [comment]
Hello!
Your `data_settings` seem fine, no issues there.

Interesting diagnosis, regarding the different sampling rates. Would you be able to try recreating this problem with just a handful of files (a few with 44.1 kHz and a few with 22.05 kHz, chosen at random) and share the same with me? Having a copy of the files would help recreate the problem on my end and would help me get to the source of the issue.
Thank you.

PS: On a side note, if your `bandwidth_clip` only goes up to 10 kHz, you can benefit (reduced processing time & memory consumption) from setting `desired_fs` to 22050 Hz instead of 48000 Hz.

**Comment by crondeaustj** [comment]
Hi, 
Thank you for your quick reply! Yes, I have recreated the problem with just six files. How can I share them with you? I can't attach them here as this platform doesn't support WAV files. 
Best regards

**Comment by shyamblast** [comment]
Please zip the files. Then you can drag-and-drop into the comment area.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by crondeaustj** [comment]
Here you will find a zip file with three directories (representing three classes) containing each two zip files. One has two 44kHz files, the second has two 22kHz files, and the third has one of each. If you get the same problem as I do, you will see that the `clip_counts` for these directories are respectively 2, 4 and 3. Thanks for taking the time to look at it!
[Sample.zip](https://github.com/shyamblast/Koogu/files/11413773/Sample.zip)

**Comment by shyamblast** [comment]
Thanks for sharing sample files.

As it turns out, you've encountered a feature, not a bug :)
Koogu supports handling of multi-channel recordings. By default, Koogu **prepares** and uses data from every channel in an audio file.

While your other files are 1-channel recordings, your 22.05 kHz files are 2-channel recordings. Hence you're getting twice the expected number of clips for the 22.05 kHz files.

If you prefer to use specific channel(s), you don't need to use any audio-processing software to pre-extract the needed channel(s).
You can simply direct `from_top_level_dirs` to do so using the (undocumented) parameter `channels`. Pass a list of zero-based indices corresponding to the desired channel(s).
When I passed `channels=[0]` (to only use the first channel), I got the following clip counts `{'22k': 2, '44k': 2, 'mix': 2}`

Please mark the _issue_ as _closed_ if your concern was addressed.

**Comment by crondeaustj** [comment]
Yes! It works. Thank you so much for your prompt assistance, I really appreciate it!
